language: ruby
rvm:
  - "2.3.1"
  - "2.2.5"
  - "2.1.10"
  - 2.0
  - 1.9.3
  - rbx-2
  - rbx-3
  - jruby
  - jruby-9
  - jruby-19mode
  - ruby-head
  - jruby-head
before_install: gem install bundler -v 1.11.2
